# Generated by Django 5.2.8 on 2025-11-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_healthscan_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthscan",
            name="image_url",
        ),
    ]
