# Generated by Django 5.2.8 on 2025-11-28 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_healthscan_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskprediction",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="batch",
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("PESTICIDE", "Pesticide Applied"),
                            ("FUNGICIDE", "Fungicide Applied"),
                            ("IRRIGATION", "Irrigation Adjustment"),
                            ("STORAGE", "Improved Storage"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("applied_date", models.DateField()),
                ("success", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="core.cropbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="LossEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "loss_type",
                    models.CharField(
                        choices=[
                            ("PEST", "Pest Infestation"),
                            ("DISEASE", "Disease"),
                            ("WEATHER", "Weather Damage"),
                            ("STORAGE", "Storage Loss"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_loss_kg", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_events",
                        to="core.cropbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.DeleteModel(
            name="HealthScan",
        ),
        migrations.DeleteModel(
            name="RiskPrediction",
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
